CREATE TABLE dbo.Hospital_General_Information (
    Facility_ID                          VARCHAR(6),
    Facility_Name                        VARCHAR(74),
    Address                              VARCHAR(51),
    City_Town                            VARCHAR(24),
    State                                VARCHAR(2),
    ZIP_Code                             VARCHAR(8),
    County_Parish                        VARCHAR(25),
    Telephone_Number                     VARCHAR(14),
    Hospital_Type                        VARCHAR(36),
    Hospital_Ownership                   VARCHAR(43),
    Emergency_Services                   VARCHAR(3),
    Birthing_Friendly                    VARCHAR(1),
    Hospital_Overall_Rating              VARCHAR(13),
    Hospital_Overall_Rating_Footnote     VARCHAR(8),
    MORT_Group_Measure_Count             VARCHAR(13),
    Count_Facility_MORT_Measures         VARCHAR(13),
    Count_MORT_Measures_Better           VARCHAR(13),
    Count_MORT_Measures_No_Different     VARCHAR(13),
    Count_MORT_Measures_Worse            VARCHAR(13),
    MORT_Group_Footnote                  VARCHAR(8),
    Safety_Group_Measure_Count           VARCHAR(13),
    Count_Facility_Safety_Measures       VARCHAR(13),
    Count_Safety_Measures_Better         VARCHAR(13),
    Count_Safety_Measures_No_Different   VARCHAR(13),
    Count_Safety_Measures_Worse          VARCHAR(13),
    Safety_Group_Footnote                VARCHAR(7),
    READM_Group_Measure_Count            VARCHAR(13),
    Count_Facility_READM_Measures        VARCHAR(13),
    Count_READM_Measures_Better          VARCHAR(13),
    Count_READM_Measures_No_Different    VARCHAR(13),
    Count_READM_Measures_Worse           VARCHAR(13),
    READM_Group_Footnote                 VARCHAR(8),
    Pt_Exp_Group_Measure_Count           VARCHAR(13),
    Count_Facility_Pt_Exp_Measures       VARCHAR(13),
    Pt_Exp_Group_Footnote                VARCHAR(8),
    TE_Group_Measure_Count               VARCHAR(13),
    Count_Facility_TE_Measures           VARCHAR(13),
    TE_Group_Footnote                    VARCHAR(8)
);

CREATE TABLE dbo.Complications_and_Deaths (
    Facility_ID           VARCHAR(10),
    Facility_Name         VARCHAR(150),
    Address                VARCHAR(150),
    City_Town              VARCHAR(50),
    State                  VARCHAR(5),
    ZIP_Code                VARCHAR(10),
    County_Parish           VARCHAR(50),
    Telephone_Number        VARCHAR(20),
    Measure_ID              VARCHAR(30),
    Measure_Name             VARCHAR(200),
    Compared_to_National      VARCHAR(60),
    Denominator                VARCHAR(30),
    Score                       VARCHAR(30),
    Lower_Estimate               VARCHAR(30),
    Higher_Estimate               VARCHAR(30),
    Footnote                        VARCHAR(20),
    Start_Date                       VARCHAR(20),
    End_Date                          VARCHAR(20)
);

CREATE TABLE dbo.Timely_and_Effective_Care (
    Facility_ID        VARCHAR(10),
    Facility_Name      VARCHAR(150),
    Address            VARCHAR(150),
    City_Town          VARCHAR(50),
    State              VARCHAR(5),
    ZIP_Code           VARCHAR(10),
    County_Parish      VARCHAR(50),
    Telephone_Number   VARCHAR(20),
    Condition_Name     VARCHAR(60),
    Measure_ID         VARCHAR(60),
    Measure_Name       VARCHAR(400),
    Score              VARCHAR(30),
    Sample             VARCHAR(30),
    Footnote           VARCHAR(30),
    Start_Date         VARCHAR(20),
    End_Date           VARCHAR(20)
);

CREATE TABLE dbo.Unplanned_Hospital_Visits (
    Facility_ID              VARCHAR(10),
    Facility_Name            VARCHAR(150),
    Address                  VARCHAR(150),
    City_Town                VARCHAR(50),
    State                    VARCHAR(5),
    ZIP_Code                 VARCHAR(10),
    County_Parish            VARCHAR(50),
    Telephone_Number         VARCHAR(20),
    Measure_ID               VARCHAR(30),
    Measure_Name             VARCHAR(200),
    Compared_to_National     VARCHAR(60),
    Denominator              VARCHAR(30),
    Score                    VARCHAR(30),
    Lower_Estimate           VARCHAR(30),
    Higher_Estimate          VARCHAR(30),
    Number_of_Patients       VARCHAR(30),
    Number_of_Patients_Returned VARCHAR(30),
    Footnote                 VARCHAR(20),
    Start_Date               VARCHAR(20),
    End_Date                 VARCHAR(20)
);

CREATE TABLE dbo.Healthcare_Associated_Infections (
    Facility_ID           VARCHAR(10),
    Facility_Name         VARCHAR(150),
    Address                VARCHAR(150),
    City_Town               VARCHAR(50),
    State                    VARCHAR(5),
    ZIP_Code                  VARCHAR(10),
    County_Parish              VARCHAR(50),
    Telephone_Number            VARCHAR(20),
    Measure_ID                   VARCHAR(30),
    Measure_Name                  VARCHAR(200),
    Compared_to_National            VARCHAR(60),
    Score                             VARCHAR(30),
    Footnote                          VARCHAR(20),
    Start_Date                        VARCHAR(20),
    End_Date                          VARCHAR(20)
);